name: ci # 
on:
  push:
    branches: # 
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
          
      - run: apt update #
      - run: apt install software-properties-common #
      - run: add-apt-repository ppa:deadsnakes/ppa #
      - run: apt install python3.9 python3-pip #
      - run: docker pull foliant/foliant #
      - run: pip install mkdocs-material #
      - run: pip install foliant foliantcontrib.init #
      - run: foliant make site
